---
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html

# 1. check if upgrade needs to happen
- name: get file info
  command: 'docker ps'
  register: docker

- debug:
    msg: "Node has already been upgraded, skipping."
  when: node_version in docker.stdout

- name: upgrade Aptos
  when: node_version not in docker.stdout
  block:
    - name: Upgrade message
      debug:
        msg: "Node version has changed, upgrading..."
      when: node_version not in docker.stdout

    - name: Change image tag
      become: true
      lineinfile:
        path: '{{ aptos_dir }}/docker-compose.yaml'
        regexp: '^    image: '
        line: '    image: "${VALIDATOR_IMAGE_REPO:-aptoslabs/validator}:${IMAGE_TAG:-{{ node_version }}}"'
        state: present
