---
- name: check cli version
  shell: "/usr/local/bin/aptos -V"
  register: aptos_version
  ignore_errors: true

- name: build new version & install
  when: '(aptos_cli_version not in aptos_version.stdout) or (aptos_version.stdout == "")'
  block:
    - name: update aptos repo for node install
      git:
        repo: "{{ repo }}"
        dest: "{{ user_dir }}/aptos"
        version: "{{ aptos_cli_branch }}"
        update: true
        force: true
        recursive: true

    - name: Run/update Aptos prep script
      command: "{{ item }}"
      args:
        chdir: "{{ user_dir }}/aptos"
      with_items:
        - "nice -n 15 ./scripts/dev_setup.sh -b"
      environment:
        PATH: "{{ path }}"

    - name: build aptos and aptos-node
      command: "{{ item }}"
      args:
        chdir: "{{ user_dir }}/aptos"
      with_items:
        - "nice -n 15 cargo clean"
        - "nice -n 15 cargo build --package aptos --profile release"
        - "nice -n 15 cargo build --package aptos-node --profile release"
      environment:
        PATH: "{{ path }}"

    - name: copy binaries
      become: true
      copy:
        src: "{{ user_dir }}/aptos/target/release/{{ item }}"
        dest: "/usr/local/bin"
        owner: root
        group: root
        mode: 0755
        remote_src: true
      loop:
        - aptos
        - aptos-node
