---
- name: install prerequisites
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: Update aptos repo for use for setup script
  git:
    repo: "{{ repo }}"
    dest: "{{ user_dir }}/aptos"
    version: main
    update: true
    force: true

- name: Run/update Aptos prep script
  command: "{{ item }}"
  args:
    chdir: "{{ user_dir }}/aptos"
  with_items:
    - "nice -n 15 ./scripts/dev_setup.sh -b"
  environment:
    PATH: "{{ path }}"
