---
- name: install prerequisites
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent
      - software-properties-common
      - apparmor-utils
    update_cache: yes
