---
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html

# 1. check if upgrade needs to happen
- name: get file info
  become: true
  command: 'cat {{ aptos_dir }}/docker-compose.yaml'
  register: docker

- debug:
    msg: "Node version has changed, upgrading..."
  when: node_version not in docker.stdout

- name: upgrade Aptos
  when: node_version not in docker.stdout
  block:
    - name: Upgrade message
      debug:
          msg: "Node has already been upgraded, skipping."
    - name: Change image tag
      become: true
      lineinfile:
        path: '{{ aptos_dir }}/docker-compose.yaml'
        regexp: '^    image: '
        line: '    image: "${VALIDATOR_IMAGE_REPO:-aptoslabs/validator}:${IMAGE_TAG:-{{ node_version }}}"'
        state: present

    - name: Pull latest version
      community.docker.docker_compose:
        project_src: '{{ aptos_dir }}'
        recreate: never
        pull: true

    - name: Restart Docker
      community.docker.docker_compose:
        project_src: '{{ aptos_dir }}'
        state: present
