---
- name: Create chain folder if it does not exist
  file:
    path: "{{ aptos_dir }}"
    state: directory
    mode: "0755"

- name: Pull waypoint.txt
  get_url:
    url: "{{ waypoint }}"
    dest: "{{ aptos_dir }}/waypoint.txt"
    mode: "0644"

- name: Pull genesis.blob
  get_url:
    url: "{{ genesis }}"
    dest: "{{ aptos_dir }}/genesis.blob"
    mode: "0644"

- name: Copy fullnode.yaml
  copy:
    src: "files/public-fullnode.yaml"
    dest: "{{ aptos_dir }}/fullnode.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  when: role == "pfn"

- name: Copy docker-compose.yaml
  template:
    src: "docker-compose-fullnode.yaml.j2"
    dest: "{{ aptos_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  when: role == "pfn"

- name: Open p2p port for full nodes
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: "{{ p2p_port_fn }}"
  when: role != "validator"

- name: Open api port
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: "{{ api_port }}"
  when: (role == "vfn") or (role == "pfn")
